### PR TITLE
Added how to use a color type with the vector4 as tint

### PR DESCRIPTION
**Pull request by Thraka**
Edited in GitHub.. I know sucks.. Things look OK though. I also adjusted the double space at the end of a sentence. We don't do that in tech writing, only formal writing like novels and letters...

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Thraka__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (adegeo). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Thraka** [comment]
**NOTE** I did not validate that it builds docs correctly. It looks correct though.

**Comment by shawnhar** [comment]
I'll check that it builds before merging :-)

**Comment by clandrew** [comment]
Thanks for this pull request! I appreciate the help with our docs.

**Comment by shawnhar** [comment]
Afraid it's not clean:

  F:\t\Win2D\win2d.proj(318,5): warning : F:\t\Win2D\tools\docs\CanvasSpriteBatch.xml : warning : bad cref target: T:Windows.UI.Color [F:\t\Win2D\tools\docs\BuildDocs.proj]
[snip repeated warnings]

    24 Warning(s)
    0 Error(s)

This is because of the use of cref to link Windows.UI.Color.  cref only works for target types within the Win2D documentation itself.

To validate the doc build, run tools\docs\builddocs.cmd from a VS 2015 MSBuild command prompt.

Thanks!

**Comment by Thraka** [comment]
OK updated the text.

I also ran **builddocs.cmd** and found one of the output files: `Win2D/bin/docs/html/M_Microsoft_Graphics_Canvas_CanvasSpriteBatch_DrawFromSpriteSheet_4.htm` and it is rendering nice.

However, the parser doesn't seem to transform the MAML inline element `<codeInline>` and I'm not sure where to configure/address that.

**Comment by shawnhar** [comment]
<codeInline> is not supported in Win2D API reference docs for the simple reason that these docs aren't in MAML format!   We're using Sandcastle plus an assortment of duct tape - the schema is basically the C# XML comment format, plus some limited support for basic HTML formatting tags.

**Comment by Thraka** [comment]
According to the spec the `<c>` tag works. Built it out and indeed it colors correctly inline. :+1:

**Comment by shawnhar** [comment]
Win2D doc style is not to do anything special to highlight type or method names.  Just leave this as straight text.

**Comment by Thraka** [comment]
Sorry, I meant the basic `///` c# spec said `<c>` was supported for inline code while `<code>` is supported for mutliline code. I wasn't speaking of the MAML spec.

Do you still want me to take it out?

**Comment by shawnhar** [comment]
I think this should follow the existing Win2D doc style, which is to use &lt;code&gt; for code examples, but not decorate API member names that occur inline within a paragraph.  We don't use the &lt;c&gt; tag at all.

**Comment by Thraka** [comment]
Done!

**Comment by clandrew** [comment]
Looked over the content, it looks good to me. Once shawnhar verifies it builds I am signed off too.

**Comment by shawnhar** [comment]
Looks good and builds cleanly.

Many thanks for the contribution!

**Pull request merged**
