### PR TITLE
Include XamlIslandSample in Win2D.proj

### PR DESCRIPTION
**Pull request by devsko**
This is gone a bit wild...
- Added Win32 configuration to XamlIslandSample projects
- Changed explicit imports of Win2D.cpp/cs.props/targets to implicit Directory.Build.props/targets to support .NET Core SDK projects
- Introduced __TargetPlatformVersion/__TargetPlatformMinVersion in Directory.Build.props as the one and only place for Windows versions
- Tweaking some backslashes in paths
- Fixing #600 - Verified that no more workarounds needed for
  - IntermediateOutputPath in test projects
  - Run of C++ UWP tests during command line build
  - NuGet restore

### CODE REVIEW

**Comment by shawnhar** [comment]
This looks good to me.  Thanks for putting it together!

I'd appreciate a sanity check from @damyanp before merging, as he originally implemented most of the build files this is touching.

**Comment by lhak** [comment]
Would it be possible to add a configuration so that the nuget package can be installed into a .net framework application?

**Comment by devsko** [comment]
@lhak That is in the pipeline but it takes time. First want to fix .NET Core scenario
But it should not be that difficult

**Comment by damyanp** [comment]
LGTM.  TIL about Directory.Build.* :)

**Pull request merged**
