### PR TITLE
Remove dead code in InkExample

### PR DESCRIPTION
**Pull request by bricelam**
Addresses #369

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bricelam__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by clandrew** [comment]
Hi, bricelam. Thanks for sending this pull request along. 

I took a look at this. It appears this event handler is only used during default drying. Since this sample always does custom drying, it'll never get raised. Here, strokes deleted-by-selection are actually deleted via InkManager.DeleteSelected, and the ink manager owns removing strokes from the collection of what gets drawn. So this code is indeed dead.

Thanks for catching this!

**Comment by clandrew** [comment]
Please consider me signed off. 

I'll see if anyone else wants to chime in, since normally we try and +2 all PRs. If we're good, then I'll merge the PR.

**Comment by clandrew** [comment]
Thanks for your help!

**Comment by bricelam** [comment]
W00t, I've contributed to one of my favorite open source projects! :wink: Keep up the awesome work.

**Pull request merged**
