### PR TITLE
Added support for input of type System.Double

### PR DESCRIPTION
**Pull request by ratishphilip**
Classes **Vector2**, **Vector3**, **Vector4**, **Matrix3x2**, **Matrix4x4**, **Plane** &
**Quaternion** will also accept input of type **System.Double** along with **float**.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ratishphilip__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by shawnhar** [comment]
Hello,

This numerics code in Win2D is actually only a clone of the System.Numerics.Vectors assembly which is part of .NET CoreFX.  That master code lives over at https://github.com/dotnet/corefx/tree/master/src/System.Numerics.Vectors, and would be the right place to propose this change.

Win2D directly uses System.Numerics.Vectors when building for UWP (Win10+).  It only includes this local copy of the numerics code to support older operating system (Windows 8.1 and Phone 8.1).

I don't think we'll want to take any new features into the Win2D copy of the code unless they were first accepted into the master System.Numerics.Vectors version.

**Comment by shawnhar** [comment]
I should add that I'm not 100% convinced it's a good idea to provide methods that silently reduce precision.   C# is generally pretty consistent that any time you convert a larger or more precise value to something with fewer bits, and explicit cast should be required.

But, the main System.Numerics.Vectors github project is the right place to have this discussion.

**Comment by ratishphilip** [comment]
Thanks Shawn. I shall ask this question in the  main System.Numerics.Vectors github project.

**Comment by shawnhar** [comment]
Based on the resolution to https://github.com/dotnet/corefx/issues/8007, I think this is no longer an active request so I'm going to close the pull request.

**Pull request closed without merging**
