### PR TITLE
Added VB to the Introduction

### PR DESCRIPTION
**Pull request by Nukepayload2**
Added "VB" to the Introduction and inserted a code example for VB.
Associated issue: #396

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Nukepayload2__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by shawnhar** [comment]
Thanks for putting this together!

This same introduction paragraph also occurs in the file winrt\docsrc\Introduction.aml, which generates the documentation that ends up at http://microsoft.github.io/Win2D/html/Introduction.htm.  May be worth updating that version as well?

**Comment by clandrew** [comment]
I took a look at this as well. Looks good to me.

**Comment by shawnhar** [comment]
Many thanks!  I'm merging this to master now.  The readme.md change will show up on the Win2D homepage right away, while the doc introduction will update the next time we release a new build of Win2D.

**Pull request merged**
