### PR TITLE
Update team blog link. Fix #411

### LINKED ISSUE #411: The link to the team blog in the readme.md is broken
It should link to https://blogs.msdn.microsoft.com/win2d/

The existing link might have worked before, or maybe it still works if you're logged into certain Microsoft accounts, but it just errors out for me.

### PR DESCRIPTION
**Pull request by Devinsuit**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Devinsuit__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Devinsuit** [comment]
@shawnhar, yes, of course.

**Comment by shawnhar** [comment]
Quick update on this - I have a ticket open with the MSDN blogs team to understand why the URL has changed and older links are no longer working.  We'll merge this PR if they conform that the blog change was intentional.

**Comment by shawnhar** [comment]
Hi - I'm curious why you closed this pull request?  We were planning on merging it - I'm just trying to find out why the blog configuration has changed first (sorry that is taking so long)

**Comment by Devinsuit** [comment]
I accidentally deleted the repository that submitted this pull request. When you find out why the blog configuration has changed, I'll commit again.

**Comment by shawnhar** [comment]
Hey there - sorry it's taking so long to get an authoritative answer on why this changed!  We are fed up waiting for that, so decided to just ahead and make this change even without yet understanding /why/ it seems to be needed :-)

If you still have the changes handy, please reactivate the PR and we will merge it.  Don't worry if not, though - we can easily repeat the change ourselves.  Want to give you the chance to get credit for the fix first though!

**Comment by Devinsuit** [comment]
https://github.com/Microsoft/Win2D/pull/419

**Pull request closed without merging**
