### PR TITLE
Add support for .NET Framework to nuget package

### PR DESCRIPTION
**Pull request by devsko**
cc @lhak Please let me know if this works for you.

### CODE REVIEW

**Comment by lhak** [comment]
I had to change some lines in the targets file as shown below to avoid an error ("No implementation file found for Microsoft.Graphics.Canvas.winmd"):

```
<Reference Include="$(MSBuildThisFileDirectory)..\..\lib\net462\Microsoft.Graphics.Canvas.winmd">
  <Implementation>Microsoft.Graphics.Canvas.dll</Implementation>
</Reference>
```
With this change it is working fine. Thank you very much!

**Comment by devsko** [comment]
@lhak Hmm. That should work with the existing AddNativeImplementation target and it works for me? Do you have a binlog (msbuild /bl)

**Comment by lhak** [comment]
I have attached a log file:

[msbuild.zip](https://github.com/Microsoft/Win2D/files/2902309/msbuild.zip)

**Comment by devsko** [comment]
@lhak Ok. It seems things are different because you use packages.config. I only tested PackageReference. I will have a look tomorrow.

**Pull request merged**
